version: '3'

services:
  nginx:
    image: nginx:1.23-alpine
    ports:
      - "8080:80"
    volumes:
      - ./:/app
      - ./docker/nginx:/etc/nginx/conf.d
    depends_on:
      - app

  app:
    build: .
    volumes:
      - ./:/app
    depends_on:
      - postgres

  postgres:
    image: postgres:15.1-alpine
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}


